services:
  postgres-db:
    image: postgres:latest
    container_name: meu-postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_eventos
#    volumes:
#      - postgres-data-local:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s       # Tenta a cada 10 segundos
      timeout: 5s
      retries: 5         # Aumentamos as tentativas para 10
      start_period: 30s   # <-- A GRANDE MUDANÃ‡A

  api-spring:
    container_name: api-eventos
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/db_eventos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      postgres-db:
        condition: service_healthy

#volumes:
#  postgres-data-local: